Changed outdated information of the tutorial
eclipse-4diac/4diac-documentation pull request #33
Opened 2024-04-30 14:35 UTC by PStmmr

2024-05-03 07:21 UTC, azoitl commented
you removed several images from the docs, can you please also delete them and commit that so that we have old pictures in the repo nobody needs anymore.

2024-05-03 08:07 UTC, MartinMelikMerkumians requested changes

2024-05-03 08:07 UTC, MartinMelikMerkumians commented on src/tutorials/distribute4diac.adoc
> +. The command looks like this: forte.exe -c localhost:port
forte.exe, here and in line 109 is specific to Windows builds. is this on purpose or should this better be replaces with some other term like "forte executable"?

2024-05-03 08:07 UTC, MartinMelikMerkumians commented on src/tutorials/distribute4diac.adoc
> +Open the local console 2x
I think it would be easier to read it this would read
Open two local consoles

2026-05-23 20:56 UTC, azoitl approved these changes
Rebased and fixed merge conflicts. Sorry that it took so long.

2026-05-23 20:56 UTC, merged